### ISSUE TITLE
Support docs.rs

### ISSUE THREAD

**Issue by jmcomets** [Cldfire/ayu-rs#1]
I don't know how different the styles from [docs.rs][] are, but I'm sure that this can be improved by supporting it. 😄 

[docs.rs]: https://docs.rs

**Comment by Cldfire** [comment]
It does! Docs.rs was the first site I built this for :)

**Comment by jmcomets** [comment]
That's weird, I have `@-moz-document domain("rust-lang.org")` in my user styles when installing it.

**Comment by jmcomets** [comment]
For some reason I installed the theme from [here](https://userstyles.org/styles/111658/darker-rust) instead of the one from this repo. In the end I added the styles manually in stylish.

**Comment by Cldfire** [comment]
Yep, I don't have this on userstyles.org yet. Taking care of that shortly (#5)
