### ISSUE TITLE
Support rustbyexample.com

### ISSUE THREAD

**Issue by VoidNoire** [Cldfire/ayu-rs#10]
Maybe something like https://userstyles.org/styles/138041/rust-by-example-dark

**Comment by Cldfire** [comment]
Thanks for the suggestion! I definitely agree that this site should be supported. Next time I'm working on this theme I will try to get this done.

**Comment by VoidNoire** [comment]
That's good to hear. I edited the style from my previous post to include darker backgrounds for the editor's current line and highlighted text and uploaded it at https://userstyles.org/styles/145142/dark-rust-by-example in case you're interested. I'm thinking I should change the editor's syntax highlighting theme to something that pops out better in darker backgrounds too.

**Comment by Cldfire** [comment]
Status update: RBE is currently being ported to mdBook (https://github.com/rust-lang/rust-by-example/pull/897). Newer versions of mdBook ship with a version of the Ayu theme that I contributed (https://github.com/azerupi/mdBook/pull/315), so when the live RBE site is built via mdBook, anyone will be able to select that theme on any device (yay!).

That means there's very little for me to do here in this project to support RBE. The only part that would need to be themed via stylish is the Ace editor itself as the mdBook project is currently using non-Ayu code block styling when the Ayu theme is active (https://github.com/azerupi/mdBook/blob/0226da91e4e52beb9866563ef54b428b0d0d1b71/src/theme/book.js#L138-L144).

In the long-term it would be nice to fix the look in mdBook itself with a proper Ace Ayu theme, although in the short term I will likely just fix it here via stylish.

**Comment by Cldfire** [comment]
Styling for the Ace editor on rustbyexample was just added in d22ec37235a6f24a0f003061a4c4d4c49e72c6f5 and is live on the Stylish theme. Update and enjoy!
