### ISSUE TITLE
docs.rs top menu bar not styled

### ISSUE THREAD

**Issue by yodaldevoid** [Cldfire/ayu-rs#15]
Using Stylus, Firefox 56.0, Ubuntu 17.10

![image](https://user-images.githubusercontent.com/1204409/37616955-ebd77c32-2b87-11e8-8564-afae78362583.png)

**Comment by Cldfire** [comment]
Fixed along with another few small issues and released on userstyles 👍 

Thanks again for bringing this to my attention. Please don't hesitate to report any more issues you encounter 😄
