### ISSUE TITLE
Support Night Mode for https://blog.rust-lang.org/

### ISSUE THREAD

**Issue by DeltaManiac** [Cldfire/ayu-rs#16]
Can a PR be submitted for the changes that are specified in this issue for Night Mode for Rust Programming Language Blog?
[Night Mode](https://github.com/rust-community/rust-lang-blog-boilerplate/issues/3)

**Comment by Cldfire** [comment]
Hello! Thanks for bringing this to my attention, I appreciate it.

I think it would be really cool to put a PR together for this. I would definitely want to put a bit more work into it, though; based on the screenshot you posted in that thread, it looks like the syntax highlighting needs to be fixed (which should be fairly simple to bring over from the rustdoc or ace themes) as well as possibly a few other things.

I've got quite a bit going on in my life right now (which seems to be becoming a common theme for me 😮), but I think I should be able to get this done sometime in the near future. We'll see!

Thanks again for the suggestion :)

**Comment by Cldfire** [comment]
Closed by #17.
