### ISSUE TITLE
Override bootstrap colors

### ISSUE THREAD

**Issue by jmcomets** [Cldfire/ayu-rs#2]
As you'll notice on the following screenshot (taken from [here](https://users.rust-lang.org/t/dark-ayu-theme-for-rustdoc-and-docs-rs/9289/3)), the `alert-info` class insert an ugly light blue which conflicts with the dark background. There's also the various `btn-*` classes that have the same color issue.

![screenshot](https://cloud.githubusercontent.com/assets/1894019/22625198/e1f9e5c6-eb8f-11e6-9a31-c1d8cd9d6e7c.png)

Maybe we can use steal the colors from one of the dark [bootswatch](https://bootswatch.com) themes?

**Comment by Cldfire** [comment]
I haven't made any effort to support the user forums yet, but I will likely look into that soon. Right now I'm working on support for both the official rust playground and integer32's playground. 

Which reminds me, I should make and issue for that.

**Comment by Cldfire** [comment]
Closing this as it does not apply to this theme.

**Comment by jmcomets** [comment]
Sorry to nag about this, but I do have the same problem with the correct theme.

**Comment by Cldfire** [comment]
Well the theme in this repository is only for rustdoc and Docs.rs currently. Trying to use it on the user forums will probably yield awful results (I haven't even tried it there).

**Comment by jmcomets** [comment]
It does, and I suggest not using them there. :D
