### ISSUE TITLE
Can't use style with rustdoc or cargo doc

### ISSUE THREAD

**Issue by Evanjs** [Cldfire/ayu-rs#23]
I am trying to use this theme with cargo doc, but am having issues.

`rustdoc --themes` fails to use rustdoc.css, and `rustdoc --theme-checker` cites numerous missing rules
``` bash
$ rustdoc -Z unstable-options --theme-checker ~/src/rustdoc_styles/ayu.css 
rustdoc: [theme-checker] Starting tests!
 - Checking "/home/evanjs/src/rustdoc_styles/ayu.css"... FAILED
  Missing ".stab.internal" rule
  Missing ".sidebar-title" rule
  Missing ".content .highlighted.fn, .content .highlighted.method, .content .highlighted.tymethod" rule
  Missing ".modal-content" rule
  Missing ".content .highlighted.trait" rule
  Missing "pre.ignore:hover, .information:hover + pre.ignore" rule
  Missing ".search-failed a" rule
  Missing ".docblock table th" rule
  Missing ":target > .in-band" rule
  Missing ".content span.union, .content a.union, .block a.current.union" rule
  Missing ".content span.primitive, .content a.primitive, .block a.current.primitive" rule
  Missing ".modal-content > .whiter" rule
  Missing "nav.main .current" rule
  Missing ".information > .ignore:hover" rule
  Missing ".stab.internal a" rule
  Missing "pre.compile_fail:hover, .information:hover + pre.compile_fail" rule
  Missing "pre.rust .lifetime" rule
  Missing ".content .highlighted.foreigntype" rule
  Missing "tr.result span.primitive::after, tr.result span.keyword::after" rule
  Missing ".tooltip.ignore" rule
  Missing "h1, h2, h3:not(.impl):not(.method):not(.type):not(.tymethod), h4:not(.method):not(.type):not(.tymethod)" rule
  Missing ".content .highlighted.primitive" rule
  Missing ".tooltip .tooltiptext::after" rule
  Missing ".stab.unstable" rule
  Missing "h1.fqn" rule
  Missing "h2, h3:not(.impl):not(.method):not(.type):not(.tymethod), h4:not(.method):not(.type):not(.tymethod)" rule
  Missing "nav.main .separator" rule
  Missing ".since" rule
  Missing "pre.rust .kw" rule
  Missing "#titles > div:not(.selected)" rule
  Missing ".line-numbers :target" rule
  Missing ".modal-content > .close:hover + .whiter" rule
  Missing ".collapse-toggle" rule
  Missing ".docblock table td" rule
  Missing "#titles > div > div.count" rule
  Missing ".modal-content > .close:hover" rule
  Missing "#crate-search + .search-input" rule
  Missing ".modal-content > .close" rule
  Missing ".content .highlighted.struct" rule
  Missing ".content .highlighted.enum" rule
  Missing ".content .highlighted.mod, .content .highlighted.externcrate" rule
  Missing ".content .highlighted.keyword" rule
  Missing ".content span.keyword, .content a.keyword, .block a.current.keyword" rule
  Missing "@media (max-width: 700px)" rule
  Missing ".content .highlighted" rule
  Missing "pre.rust .kw-2, pre.rust .prelude-ty" rule
  Missing ".docblock:not(.type-decl) a:not(.srclink):not(.test-arrow), .docblock-short a:not(.srclink):not(.test-arrow), .stability a" rule
  Missing ":target > code" rule
  Missing "pre.compile_fail" rule
  Missing ".docblock table" rule
  Missing ".sidebar .current" rule
  Missing "pre.rust .macro, pre.rust .macro-nonterminal" rule
  Missing "pre.rust .doccomment" rule
  Missing "pre.rust .question-mark" rule
  Missing ".toggle-label" rule
  Missing ".stab.deprecated" rule
  Missing ".content span.constant, .content a.constant, .block a.current.constant, .content span.static, .content a.static, .block a.current.static" rule
  Missing ".source .sidebar" rule
  Missing ".sidebar" rule
  Missing "pre.ignore" rule
  Missing ".tooltip.compile_fail" rule
  Missing ".stab.portability" rule
  Missing ".content .highlighted a, .content .highlighted span" rule
  Missing ".content .highlighted.union" rule
  Missing "pre.rust .self, pre.rust .bool-val, pre.rust .prelude-val, pre.rust .attribute, pre.rust .attribute .ident" rule
  Missing ".content .method .where, .content .fn .where, .content .where.fmt-newline" rule
  Missing ".important-traits .tooltip .tooltiptext" rule
  Missing "#titles > div:hover, #titles > div.selected" rule
  Missing ".invisible" rule
  Missing ".example-wrap > pre.line-number" rule
  Missing ".modal" rule
  Missing ".sidebar .version" rule
  Missing ".in-band" rule
  Missing ".information > .compile_fail:hover" rule
  Missing ".content .highlighted.type" rule
  Missing ".content .highlighted.attr, .content .highlighted.derive, .content .highlighted.macro" rule
  Missing ".content span.foreigntype, .content a.foreigntype, .block a.current.foreigntype" rule
  Missing ".content span.attr, .content a.attr, .block a.current.attr, .content span.derive, .content a.derive, .block a.current.derive, .content span.macro, .content a.macro, .block a.current.macro" rule
  Missing ".content .highlighted.constant, .content .highlighted.static" rule
  Missing "#crate-search" rule
```

I've also tried the steps listed [here](https://blog.guillaume-gomez.fr/articles/2016-09-16+Generating+doc+with+rustdoc+and+a+custom+theme), for using `cargo doc`, but this also fails.
Input:
`RUSTDOCFLAGS="-Z unstable-options --extend-css ~/src/rustdoc_styles/ayu.css" cargo doc`
Result:
```
error: Could not document `void`.

Caused by:
  process didn't exit successfully: `rustdoc --crate-name void /home/evanjs/.cargo/registry/src/github.com-1ecc6299db9ec823/void-1.0.2/src/lib.rs --cap-lints allow --color always -o <project_path>/target/doc -L dependency=<project_path>/target/debug/deps -Z unstable-options --extend-css '~/src/rustdoc_styles/ayu.css'` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: option --extend-css argument must be a file
```
However, removing the apostrophes from `--extend-css '~/src/rustdoc_styles/ayu.css'` seems to succeed and does not produce any errors.

Any idea if I'm doing something wrong? Or is this something that needs to go upstream?

**Comment by Evanjs** [comment]
Figured it out....
`--extend-css $HOME/path_to_style` / `--extend-css /home/evanjs/path_to_style`  works fine, `--extend-css ~/path_to_style` does not.
Still wondering if this is intended behavior, though.
We can close this issue if it is.

**Comment by Cldfire** [comment]
Hi! I'm sorry you ran into this problem, thanks for opening an issue about it.

The theme checker reporting missing rules is to be expected; the CSS in this repository was meant to be applied over the existing rustdoc theme, so it doesn't override everything.

You are unable to use `rustdoc.css` as an argument to `themes` for that reason. According to the [rustdoc documentation](https://doc.rust-lang.org/rustdoc/unstable-features.html#a--themes-provide-additional-themes), anything given as a theme must style everything that the light theme does, which I do not do with my theme here in this repository. It's possible that in the future I'll rework my rustdoc CSS to support such a usecase, and I'll open a separate issue to track that.

The path issue when using `~`, though, is quite strange. I just tried it out locally on macOS and experienced the same issue you are describing. While I cannot build with `~/Desktop/ayu.css`, I can build with `/Users/Admin/Desktop/ayu.css`. Also, as you pointed out, removing the apostrophes that are getting placed around the argument to `--extend-css` results in a successful build. It definitely seems like this is a bug in the way `cargo-doc` is handling paths? I would recommend opening an issue upstream to find out as that's out of scope for this repo.

**Comment by Evanjs** [comment]
\>_> Interesting...
https://github.com/rust-lang/rust/blob/master/src/doc/rustdoc/src/command-line-arguments.md#-e--extend-css-extend-rustdocs-css
I suppose this flag is stable now, just tried this and it worked fine: `cargo rustdoc -- --extend-css ~/src/rustdoc_styles/ayu.css`

Note to self and others with the same issue, always check the official docs, first...
https://github.com/rust-lang/cargo/blob/master/src/doc/man/cargo-rustdoc.adoc#examples

One small note is that this bypasses cargo and passes the `--extend-css` argument directly to rustdoc.  I do wonder if there's something the matter with RUSTDOCFLAGS parsing, but it seems to be irrelevant for this case, at least, given the example/intended usage.

**Comment by Cldfire** [comment]
Mmm, that's unfortunate. Hopefully everything gets worked out soon!
