### ISSUE TITLE
Crates header isn't styled, crates.io updated

### ISSUE THREAD

**Issue by DianaNites** [Cldfire/ayu-rs#30]
![Screenshot_20200429_143559](https://user-images.githubusercontent.com/5275194/80633438-cb27e080-8a26-11ea-9ac0-e46f8746a932.png)

**Comment by Cldfire** [comment]
Thank you! I released the fixes on userstyles, make sure you update your theme.

**Comment by DianaNites** [comment]
Thank you! Works perfectly now!
