### ISSUE TITLE
Install from GitHub repo instead of userstyles.org

### ISSUE THREAD

**Issue by teohhanhui** [Cldfire/ayu-rs#31]
Most UserCSS authors have been moving away from userstyles.org - why? - because they are the same people behind Stylish, which has gone rogue.

It is possible (and recommended) to serve the file directly from the GitHub repo: https://github.com/openstyles/stylus/wiki/UserCSS-authors#hosting-a-usercss

**Comment by Cldfire** [comment]
Thanks so much for the suggestion, I didn't know that was a thing!

I set everything up in 1af638ffea2028792f30012517f4f4f4aa3200f2, you should be able to click the badge and install it directly now.

Enjoy :smile:

**Comment by KiriosK** [comment]
Is this problem solved?
Just tried to use this installation and got redirected to the raw css file.

**Comment by Cldfire** [comment]
> 
> 
> Is this problem solved?
> Just tried to use this installation and got redirected to the raw css file.

Do you have https://github.com/openstyles/stylus installed in your browser?

**Comment by KiriosK** [comment]
Sorry for bothering, was a problem with extension on my side

**Comment by Cldfire** [comment]
No worries! :)
