### ISSUE TITLE
Coverage on docs.rs needs styling

### ISSUE THREAD

**Issue by Nemo157** [Cldfire/ayu-rs#33]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/81079/90015615-22398480-dca9-11ea-94b9-1c7aa403d6f4.png">

docs.rs has just added a coverage display, and it seems a little out of place being brighter than everything else in the release sidebar.

**Comment by Cldfire** [comment]
Thanks for filing an issue! :)
