### ISSUE TITLE
docs.rs portability inline notes unreadable

### ISSUE THREAD

**Issue by jakubdabek** [Cldfire/ayu-rs#35]
![image](https://user-images.githubusercontent.com/29653525/90288075-67acac00-de79-11ea-974c-56ec676599d4.png)

See the `feature=...` notes. They are styled by default under `.stab.portability>code` (for some reason).

Taken from https://docs.rs/tokio/0.2.22/tokio/index.html

**Comment by Cldfire** [comment]
Fixed. There are still some issues with the background color / padding but I don't feel like it's worth the effort to fix those as the ayu theme built into rustdoc is becoming more and more available.

I'm going to be removing the rustdoc theme from this repo soonish.
