### ISSUE TITLE
playground share links unreadable

### ISSUE THREAD

**Issue by jakubdabek** [Cldfire/ayu-rs#37]
![image](https://user-images.githubusercontent.com/29653525/90396707-fb0ef880-e096-11ea-8eef-246cd61493bc.png)

**Comment by jakubdabek** [comment]
Maybe styling all links by default would fix a lot of these issues?

**Comment by Cldfire** [comment]
Yep! Thanks for the reports, all links in the output section should be styled nicely now.

Also cleaned up the copy icons while I was at it :)
